const String poleBiographyTitle = "Vie de Cheikh Ahmed Tijani, qu’ALLAH l’agrée";

const String poleBiographyContent = """
<h3>Son enfance</h3>
<p>À ‘Aïn Madhi, un petit village situé dans le désert algérien à quelques kilomètres de Laghouat, se trouvait une humble demeure traditionnelle en terre. La modestie des lieux cachait en son sein une jeune épouse qui, dans un coin de sa maison et avec tout le courage qui caractérise les femmes de ces régions, venait d’enfanter un garçon qu’elle prénomma Ahmed. C’est ainsi qu’en 1150 de l’Hégire (1737/38) vint au monde Seïdina Ahmed Ibn Mohammed Ibn Mokhtar Tidjani (qu’Allah sanctifie son précieux secret).</p>
<p>Cet endroit isolé, loin des tumultes des grandes villes, s’était déjà fait remarquer depuis plusieurs années par l’envergure de ses savants et leur piété. L’illustre Cheikh ‘Abdallah ibn Mohammed El ‘Iyachi (m. en 1090), qui passa par ce village, en fit mention dans son écrit Rihlata. Il rencontra également Sidi Ahmed, l’arrière grand-père de Seïdina (qu’Allah l’agrée) dont il hérita du prénom, et il le décrivit par les termes élogieux de : « grand savant ».</p>
<p>Le père de Seïdina (qu’Allah l’agrée), Sidi Mohammed ibn Mokhtar, était un savant scrupuleux, aimé et respecté. Enraciné dans la Sunna, c’était un évocateur et un enseignant dans les domaines de l’exégèse et du Hadith. Il appelait et exhortait les gens au bien en les incitant à l’application de la Sunna et en combattant toute innovation sans craindre, pour Allah, le tort de quiconque. Il lui arrivait de recevoir la visite d’entités spirituelles « Rouhani » qui lui proposaient de répondre à ses besoins. Il refusait leurs propositions et les rejetait en leur disant : « Laissez-moi donc avec Allah ! Je ne désire aucune autre attache que la sienne, je n’ai nullement besoin de vous » et ils le laissaient. Il était fermement attaché à Allah et possédait dans sa demeure une pièce réservée à l’évocation. Il était lui-même issu d’une branche comptant de nombreux savants et saints accomplis.</p>
<p>Nous pouvons à titre d’exemple citer le trisaïeul de Seïdina (qu’Allah l’agrée), Sidi Mohammed qui fut le premier à se rendre et à s’installer à ‘Aïn Madhi où il se maria avec une femme de la tribu des Banou Toujine. Il fut lui aussi un grand savant et possédait dans sa demeure une pièce lui servant de lieu de retraite spirituelle dans laquelle personne d’autre que lui n’avait le droit d’entrer.</p>
<p>Il avait pour habitude de se voiler le visage lorsqu’il sortait de sa demeure afin de se rendre à la mosquée et restait ainsi voilé jusqu’à son retour au sein de sa cellule d’isolement. Lorsque Seïdina (qu’Allah l’agrée) fut interrogé au sujet de la raison pour laquelle son aïeul se voilait le visage devant les gens, il répondit : « Il se peut que cela soit du fait qu’il ait atteint un certain degré dans la sainteté. Ce degré avait en effet pour conséquence que tous ceux qui le regardaient ne pouvaient plus s’empêcher de le contempler un seul instant au risque d’en mourir. Or il comptait parmi les détenteurs de cette particularité qu’il acquit durant vingt-trois années, caractéristiques de ceux qui eurent atteint soixante-douze des sciences Mohammadienne. C’est donc pour l’ensemble de ces raisons que volontairement il se voilait le visage. »</p>

<h3>Ses Nobles Origines</h3>
<p>Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) fut mis au monde par la pieuse et pure Dame ‘Aïcha, fille de Sidi Mohamed Senoussi Tidjani Madaoui. Par ailleurs c’est du côté sa parenté maternelle que Seïdina (qu’Allah l’agrée) tire l’origine de son nom. Elle était une femme pieuse et dévouée aux qualités rares et précieuses. Elle consacrait la majeure partie de ses jours et de ses nuits à évoquer Allah ainsi qu’à prier sur le Prophète (que la prière et la paix d’Allah soient sur lui). Elle était une mère attentionnée, débordante d’amour et de miséricorde. Elle eut également plusieurs autres enfants, filles et garçons, qui moururent en bas âge. Elle accueillit ces épreuves avec résignation et foi en la récompense Divine. Ainsi, parmi ses enfants, seules survécurent une fille nommée Rouqayya, puis Seïdina (qu’Allah sanctifie son précieux secret) et enfin un garçon du nom de Mohammed, mais qui reçut le surnom d’Ibn ‘Omar, car celui-ci était versé dans le domaine de la science et du Qoran.</p>
<p>Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) était d’ascendance Chérifienne, c’est-à-dire que sa généalogie remontait jusqu’au bien aimé Prophète (que la prière et la paix d’Allah soient sur lui), par Seïdina ‘Ali et Fatima (qu’Allah les agrée) via leur fils Hassan (qu’Allah l’agrée). Cependant, il ne se fia pas aux ouï-dire ni à ce qui était mentionné dans son certificat généalogique, jusqu’à ce qu’il eut lui-même l’occasion d’interroger le bien aimé Prophète (que la prière et la paix d’Allah soient sur lui) à l’état de veille. En effet, il a dit (qu’Allah sanctifie son précieux secret) : « J’ai interrogé le maître de l’existence au sujet de mon ascendance, étais-je un Chérif ou pas ? Et concernant la tribu de la ville où je suis né et qui se réclamait d’ascendance chérifienne, quel en était la réalité ? Il m’a répondu (que la prière et la paix d’Allah soient sur lui) : « Certainement tu es mon fils, certainement tu es mon fils, certainement tu es mon fils » et il le répéta trois fois puis ajouta (que la prière et la paix d’Allah soient sur lui) : « Ton ascendance par Hassan fils de ‘Ali est authentique ». »</p>
<p>Ce n’est que depuis cette confirmation qu’il se présentait alors en intitulant ses courriers par : « Ahmed ibn Mohammed Tidjani el Hassani »</p>
<p>Quant aux habitants de son village Seïdina (qu’Allah sanctifie son précieux secret) dit : « Le Prophète (que la prière et la paix d’Allah soient sur lui) s’est tu à leurs sujets et il ne m’a nullement confirmé l’authenticité de leur appartenance généalogique. »</p>
<p>En effet, Seïdina (qu’Allah sanctifie son précieux secret) n’était pas de leur origine, car son ancêtre ne s’installa que fortuitement auprès d’eux. Ils n’ont donc aucun lien généalogique si ce n’est par les femmes. Il fut par voie de conséquence apparenté à eux en raison de l’installation de son ascendant dans leur village. Son aïeul, Sidi Salim, est originaire de la tribu de ‘Abda aux environs de Safi, sur le littoral atlantique des côtes marocaines.</p>
<p>Ainsi, c’est dans cet environnement de foi, de science et de sainteté que naquit Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret). Il grandit certes au sein d’une humble demeure, mais elle fut le creuset d’une famille très attachée au Coran et à la sunna.</p>
<p>L’éducation du saint enfant fut confiée à l’illustre et prestigieux Mohamed Ibn Hamou Tidjani (m.1162 H) sous la conduite duquel il mémorisa le texte Coranique en entier, et ce, à l’âge de sept ans. Il était un homme pieux et enseignait aux enfants. Lui-même fit son apprentissage auprès de son Cheikh Sidi ‘Issa Bou’akaz el Madaoui Tidjani qui était un homme pieux connu pour sa sainteté et qui enseignait également aux enfants. Un jour, il révéla qu’il avait vu en songe le Seigneur Très Haut lui réciter le Qoran, du début à la fin, dans la version Warch. Son Seigneur le Très Haut lui dit ensuite : « C’est ainsi qu’il fut révélé ».</p>
<p>Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) a appris le droit musulman (fiqh) selon l’école de l’Imam Malek (qu’Allah l’agrée). Il étudia les différents traités de jurisprudence tels que le Khalil, le Risalat, le Mouqqadima d’Ibn Rouchd et le Lakhdari auprès du Connaissant d’Allah, le savant Sidi Mabrouk ibn Bou’afiya Madaoui Tidjani. Sidi Mabrouk décéda en l’an 1166 H.</p>
<p>Dès son plus jeune âge, Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) se fit remarquer par son intelligence et sa piété, ainsi que ses vertus et sa modestie. Il était assidu dans ses études et possédait une volonté surprenante. Tout ce qu’il commençait, il le finissait et tout ce qu’il entamait, il le complétait. Aucune tâche, aussi ardue soit-elle, ne l’effrayait et aucun obstacle ne pouvait le détourner de son objectif, jusqu’à en atteindre le summum. Son éveil et sa compréhension étaient Seigneuriaux et dépassaient de loin ce qui pouvait être acquis par le biais de l’apprentissage et de l’enseignement. Pendant ses cours, il devançait tous les élèves dans les domaines complexes de la jurisprudence, sans pourtant n’avoir jamais lu d’ouvrage ni avoir entendu de propos relatifs à ces sujets. Les gens de son village et ceux du désert avoisinant ainsi que les érudits venaient profiter du récipient de ses connaissances. Et alors qu’il n’était encore qu’un jeune homme, il enseignait et donnait des avis juridiques (Fatwa) dans divers domaines. L’aura de sa personnalité fascinait tous ceux qui le contemplaient et elle laissait présager un destin hors du commun.</p>
<p>Un jour, alors qu’il était encore enfant et qu’il rentrait chez lui, Seïdina (qu’Allah sanctifie son précieux secret) trouva un plat préparé par sa mère que l’on nomme « Lafet » à base de navet simplement salé et cuit. Mais, à l’exception d’une seule variété, il n’aimait pas les navets il sortit donc de chez lui très contrarié. Il rencontra son voisin qui s’appelait Sidi Gourid (qu’Allah l’agrée) un homme vertueux qui détenait la Connaissance. Ce dernier, après l’avoir interrogé et su la cause de cette contrariété, l’invita à venir manger chez lui. En entrant dans sa demeure il dit à son épouse : « Nous avons un grand invité de marque, prépare du « Rfiss » », et il s’agissait là d’un met réservé aux grandes occasions à ‘Aïn Madhi. Elle le prépara, mais fut intriguée par l’identité de ce mystérieux invité de marque. Elle regarda discrètement afin de voir ce fameux personnage, mais n’aperçut que le jeune voisin, Sidi Ahmed Tidjani (qu’Allah sanctifie son précieux secret). Elle s’exclama alors : « Quoi ! C’est le petit Ahmed ton invité de marque ?! » Il lui répondit : « Tais-toi donc ! Tu ignores l’ampleur de son destin. »</p>
<p>Une autre fois durant son enfance, tandis qu’il sortait de ses cours, il aperçut (qu’Allah sanctifie son précieux secret) une immense lumière jaillir de devant lui et qui s’étendait jusqu’au ciel. Le Prophète (que la prière et la paix d’Allah soient sur lui) apparut soudainement devant lui et l’encouragea en ces termes : « Continue, car tu es dans la vérité ». Il fut si terrifié qu’il partit se réfugier au sein de la demeure de sa tante maternelle qui se trouvait être juste à côté. Elle le couvrit et le réconforta tout en lui préparant du pain. Elle s’appelait Jourkhoum, Seïdina (qu’Allah sanctifie son précieux secret) l’aimait intensément et la considérait comme une mère. Il révéla plus tard à son sujet qu’elle était une sainte et que toutes les demandes étant accomplies auprès de sa tombe, en bien ou en mal, se voyaient immanquablement exaucées. Cela au point où il devint nécessaire de cacher l’endroit de sa sépulture aux communs des gens. Jusqu’à aujourd’hui ce lieu est inconnu de tous à ‘Aïn Madhi.</p>
<p>Il arrivait souvent à ce jeune enfant de voir en rêve le tracé de son destin. En effet, il se voyait sur un trône gérant et commandant des multitudes de créatures. Il a rapporté (qu’Allah sanctifie son précieux secret) : « J’ai vu, alors que j’étais encore petit et impubère, un trône royal que l’on semblait m’avoir préparé et sur lequel je m’assis. J’avais une immense armée que je commandais pour répondre aux besoins comme le fait un roi. »</p>

<h3>Sa Quête</h3>
<p>En 1171 H. (1757/58), âgé de 21 ans, il quitte ‘Aïn Madhi poussé par une soif incommensurable, pour Fès, la célèbre cité de la science avec notamment sa fameuse Université-Mosquée Qarawiyyine.</p>
<p>Dans cette ville se côtoyaient de grands maîtres et hommes saints que Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) entreprit de visiter afin de tirer profit de leurs enseignements spirituels ainsi que de leurs bénédictions (baraka). En effet, il considérait la recherche de la compagnie des maîtres du Soufisme comme moyen de parfaire les exigences de la Loi extérieurement et intérieurement.</p>
<p>Il avait la faculté de mémoriser ce qu’il entendait dès la première écoute. Ainsi, il connaissait par cœur et dans leur intégralité de nombreux ouvrages de jurisprudence (Fiqh) tels le Moukhtasar de Cheikh Khalil, le Tahdhib Al Baradha’i, mais aussi le Sahih Boukhari, Mouslim et le Mouwata de l’Imam Malek… Il obtint ainsi tous les diplômes lui conférant le droit d’enseigner toutes les sciences connues des musulmans de cette époque. Cependant, sa soif ne fut pas étanchée pour autant. Ses efforts, sa crainte d’Allah , sa modestie, son amour pour le vrai et son aversion du faux imposaient le respect de tous.</p>
<p>Durant toutes ces années écoulées, Cheikh Ahmed Tidjani (qu’Allah sanctifie son précieux secret) s’est affilié à plusieurs voies (6 voies) et a notamment fait la rencontre de grands Aouliya sans pour autant prendre d’eux.</p>
<p>Parmi les voies auxquelles il s’est affilié, il y a celle du célèbre Pôle connu et Chérif Hassani Maulana Taïeb ibn Mohamed de Wazzan (qu’Allah l’agrée). Il est d’ailleurs le premier parmi les maîtres que Seïdina (qu’Allah sanctifie son précieux secret) rencontra... Sidi Taïeb (qu’Allah l’agrée) lui transmit la Tariqa Wazzania...</p>

<h3>Fath El Akbar – Naissance de la voie</h3>
<p>Il rentra enfin au Maghreb et s’installa à Tlemcen au cours de la même année que celle où il effectua son pèlerinage, en 1188 H. C’est dans cette ville qu’il fit la rencontre du premier de ses futurs disciples, le grand savant Sidi Mohamed ibn Mechri (qu’Allah l’agrée)...</p>
<p>C’est justement dans ce village de Boussemghoune, alors qu’il était âgé de 46 ans, que Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) eut son plus précieux et plus majestueux prodige. Alors qu’il s’était retiré (qu’Allah l’agrée) comme à son habitude dans l’une des pièces de sa demeure, en pleine journée, il eut sa Grande Ouverture (Fath El Akbar). C’est au cours de cet instant que vint à lui (qu’Allah sanctifie son précieux secret), et à l’état de veille, le noble Prophète Mohammed (que la prière et la paix d’Allah soient sur lui).</p>
<p>Le maître de l’existence (que la prière et la paix d’Allah soient sur lui) lui annonça à l’état de veille : « Je suis désormais ton initiateur, ton Maître, aucun être humain ne prétendra être ton initiateur. Il te faut en conséquence abandonner tout ce que tu as pris précédemment de l’ensemble des voies, personne n’aura de reproche à te faire, car c’est moi qui serai ton intermédiaire auprès d’Allah et aussi ton aide ».</p>
<p>Il devint (qu’Allah sanctifie son précieux secret) le dépositaire de la voie spirituelle du bien aimé Prophète (que la prière et la paix d’Allah soient sur lui) lui-même, voie mère qui renferme en elle toutes les autres voies. C’est la Tariqa Ahmediya, Mohammediya, Ibrahimiya, Hanifiya qui contient des grâces immenses...</p>

<h3>Qoutbaniya El ‘Oudhma</h3>
<p>Ainsi, depuis sa rencontre avec le Messager d’Allah (que la prière et la paix d’Allah soient sur lui) à Boussemghoune, il ne cessa de suivre ses enseignements et son éducation tout au long de ces années, et au fur et à mesure des évènements, jusqu’au jour tant annoncé et tant prédit au cours de sa vie où il fut hissé au rang suprême de la Qoutbaniya el ‘Oudhma au mois de Mouharam de l’année 1214H.</p>
<p>Une des caractéristiques de cette station est le don au Pôle du Nom Suprême Absolu d’Allah, qui est le Nom spécifique de l’Essence Divine, et cela le protège contre le dépouillement tant redouté par les Connaissants et les Aouliya.</p>
<p>Seïdina Ahmed Tidjani (qu’Allah sanctifie son précieux secret) a expliqué que le Pôle est le représentant Suprême d’Allah le Très Haut, son délégué absolu envers la totalité de la création dans son ensemble comme dans son détail, en chaque particule la plus infime, et qu’il est chargé de l’exécution du décret du Vrai, en totale servitude intérieure et extérieure.</p>
<p>Il est le Pôle caché qui sera dévoilé à tous les saints au jour du Jugement Dernier par une voix qui clamera : « ô Gens du rassemblement ! Voici votre guide par lequel vous étiez irrigués depuis le début de la création jusqu’à maintenant ».</p>
""";
